title: Andisheh Ghasemi
description: PhD Student in Computer Science at Northeastern University
url: https://andishehghasemi.com
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Reading time (if not using plugin)
words_per_minute: 200

# Permalink structure
permalink: /blog/:year/:month/:title/

# Default front matter
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Andisheh Ghasemi"
